#!/usr/bin/env python3
"""Inject pipeline/data.json into assets/data.js and cache-bust index.html.

    python3 pipeline/ingest.py    # report exports -> pipeline/data.json
    python3 pipeline/build.py     # data.json      -> assets/data.js

The cache-busting matters in production, not just locally: index.html keeps its
URL forever, so a browser that has cached assets/data.js will keep showing
yesterday's numbers after a rebuild until the cache happens to expire. Stamping a
content hash onto each asset reference makes a changed file a changed URL, so a
reload always picks up new report data.
"""
import hashlib
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "data.json")
ASSETS = os.path.join(ROOT, "assets")
OUT = os.path.join(ASSETS, "data.js")
INDEX = os.path.join(ROOT, "index.html")

# assets referenced by index.html that should be versioned
VERSIONED = ["data.js", "core.js", "pages.js", "app.js", "styles.css"]

data = json.load(open(SRC))
payload = json.dumps(data, separators=(",", ":")).replace("</", "<\\/")

os.makedirs(ASSETS, exist_ok=True)
with open(OUT, "w") as fh:
    fh.write("/* Generated by pipeline/build.py - do not edit by hand. */\n")
    fh.write("window.DASH_DATA = %s;\n" % payload)

# one hash over every versioned asset: any change busts them all, which keeps the
# scripts and the data they expect from ever being served as a mismatched pair
digest = hashlib.sha256()
for name in VERSIONED:
    path = os.path.join(ASSETS, name)
    if os.path.exists(path):
        digest.update(open(path, "rb").read())
version = digest.hexdigest()[:10]

html = open(INDEX).read()
stamped = 0


def stamp(match):
    global stamped
    stamped += 1
    return "assets/%s?v=%s" % (match.group(1), version)


html_out = re.sub(r"assets/(%s)(?:\?v=[0-9a-f]+)?" % "|".join(re.escape(n) for n in VERSIONED),
                  stamp, html)
if html_out != html:
    open(INDEX, "w").write(html_out)

print("wrote %s (%.1f KB, %d snapshots, %d stores)"
      % (OUT, len(payload) / 1024.0, len(data.get("snapshots", [])), len(data.get("stores", []))))
print("stamped %d asset refs in index.html with ?v=%s" % (stamped, version))
