#!/usr/bin/env python3
"""Inject pipeline/data.json into assets/data.js.

    python3 pipeline/ingest.py    # report exports -> pipeline/data.json
    python3 pipeline/build.py     # data.json      -> assets/data.js
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "data.json")
OUT = os.path.join(ROOT, "assets", "data.js")

data = json.load(open(SRC))
payload = json.dumps(data, separators=(",", ":")).replace("</", "<\\/")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as fh:
    fh.write("/* Generated by pipeline/build.py - do not edit by hand. */\n")
    fh.write("window.DASH_DATA = %s;\n" % payload)

print("wrote %s (%.1f KB, %d snapshots, %d stores)"
      % (OUT, len(payload) / 1024.0, len(data.get("snapshots", [])), len(data.get("stores", []))))
